apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: nfs-media-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 10.83.101.5##
    volumeAttributes:
      server: 10.83.101.5
      share: /mnt/tank/library/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-pvc 
spec:
  storageClassName: nfs-media
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 10Gi 
