apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cf-apikey-acme 
  namespace: cert-manager
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store-scw
  target:
    name: cf-apikey-acme 
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: id:a06495ff-3726-4fa9-a18a-22a3364606e6
        version: latest_enabled
---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: prod-issuer-account-key
#   namespace: cert-manager
# spec:
#   refreshInterval: 15s
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: secret-store-scw
#   target:
#     name: prod-issuer-account-key 
#     creationPolicy: Owner
#   dataFrom:
#     - extract:
#         key: id:ec947e8a-d2f2-43b0-ab11-cccad45db485
#         version: latest_enabled
