apiVersion: v1
kind: Secret
metadata:
  name: scwsm-secret
  namespace: external-secrets
data:
  scw-secret-access-key: {{ .Values.scwSecretAccessKey | b64enc }}
  scw-access-key: {{ .Values.scwAccessKey | b64enc }}
