apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secret-store-scw
  namespace: external-secrets
spec:
  provider:
    scaleway:
      region: fr-par
      projectId: 802b6dc7-d07d-45cc-be79-8822053fdf71
      accessKey:
        secretRef:
          name: scwsm-secret
          key: scw-access-key
          namespace: external-secrets

      secretKey:
        secretRef:
          name: scwsm-secret
          key: scw-secret-access-key
          namespace: external-secrets
