apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape 
metadata:
  name: longhorn-prometheus-servicemonitor
spec:
  endpoints:
  - port: manager
  namespaceSelector:
    matchNames:
    - longhorn-system
  selector:
    matchLabels:
      app: longhorn-manager
