apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default 
  namespace: metallb-system
spec:
  addresses:
    - 10.83.101.50-10.83.101.80
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default 
  namespace: metallb-system 
