apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-truenas
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.83.101.5
  share: /mnt/hot/k8s
  mountPermissions: "0777"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
