---
- name: Update resolv.conf with new nameserver
  hosts: k3s_cluster
  become: yes
  tasks:
    - name: Backup existing resolv.conf
      copy:
        src: /etc/resolv.conf
        dest: /etc/resolv.conf.bak
        backup: yes

    - name: Update resolv.conf with new nameserver
      lineinfile:
        path: /etc/resolv.conf
        regexp: '^nameserver'
        line: 'nameserver 10.83.100.2'
        state: present
        insertbefore: BOF

    - name: Remove any other nameservers if present
      lineinfile:
        path: /etc/resolv.conf
        regexp: '^nameserver'
        line: ''
        state: absent
      when: item != 'nameserver 10.83.100.2'
      loop: "{{ lookup('file', '/etc/resolv.conf').splitlines() }}"
